[debug] [2019-04-25T18:36:42.785Z] ----------------------------------------------------------------------
[debug] [2019-04-25T18:36:42.787Z] Command:       /usr/local/bin/node /usr/local/bin/firebase serve
[debug] [2019-04-25T18:36:42.788Z] CLI Version:   6.7.1
[debug] [2019-04-25T18:36:42.788Z] Platform:      darwin
[debug] [2019-04-25T18:36:42.788Z] Node Version:  v10.15.0
[debug] [2019-04-25T18:36:42.788Z] Time:          Thu Apr 25 2019 13:36:42 GMT-0500 (Central Daylight Time)
[debug] [2019-04-25T18:36:42.788Z] ----------------------------------------------------------------------
[debug] 
[debug] [2019-04-25T18:36:42.799Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2019-04-25T18:36:42.799Z] > authorizing via signed-in user
[debug] [2019-04-25T18:36:42.799Z] [iam] checking project twitter-graph-codecamp for permissions ["firebase.projects.get"]
[debug] [2019-04-25T18:36:42.802Z] > refreshing access token with scopes: ["email","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","openid"]
[debug] [2019-04-25T18:36:42.802Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>
[debug] [2019-04-25T18:36:43.161Z] <<< HTTP RESPONSE 200
[debug] [2019-04-25T18:36:43.183Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/twitter-graph-codecamp:testIamPermissions  

[debug] [2019-04-25T18:36:43.445Z] <<< HTTP RESPONSE 200
[debug] [2019-04-25T18:36:43.447Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/twitter-graph-codecamp  
 
[debug] [2019-04-25T18:36:43.681Z] <<< HTTP RESPONSE 200
[info] 
[info] === Serving from '/Users/c3po/Documents/twitter-graph-back'...
[info] 
[debug] [2019-04-25T18:36:45.761Z] Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/logs'
    at Object.mkdirSync (fs.js:753:3)
    at Object.assertLogsPath (/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/emulator/logs.js:65:10)
    at new Controller (/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/cli/controller.js:77:32)
    at FunctionsEmulator.start (/usr/local/lib/node_modules/firebase-tools/lib/functionsEmulator.js:102:23)
    at Object.start (/usr/local/lib/node_modules/firebase-tools/lib/serve/functions.js:7:33)
    at /usr/local/lib/node_modules/firebase-tools/lib/serve/index.js:15:23
    at arrayMap (/usr/local/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:639:23)
    at Function.map (/usr/local/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:9556:14)
    at _serve (/usr/local/lib/node_modules/firebase-tools/lib/serve/index.js:13:26)
    at Command.module.exports.Command.description.option.option.option.option.before.action [as _action] (/usr/local/lib/node_modules/firebase-tools/lib/commands/serve.js:55:12)
[error] 
[error] Error: An unexpected error has occurred.
